INDIAN_CITY_STATE = {
  "Mumbai": "Maharashtra",
  "Delhi": "Delhi",
  "Bengaluru": "Karnataka",
  "Hyderabad": "Telangana",
  "Ahmedabad": "Gujarat",
  "Chennai": "Tamil Nadu",
  "Kolkata": "West Bengal",
  "Pune": "Maharashtra",
  "Jaipur": "Rajasthan",
  "Surat": "Gujarat",
  "Lucknow": "Uttar Pradesh",
  "Kanpur": "Uttar Pradesh",
  "Nagpur": "Maharashtra",
  "Indore": "Madhya Pradesh",
  "Bhopal": "Madhya Pradesh",
  "Patna": "Bihar",
  "Vadodara": "Gujarat",
  "Ludhiana": "Punjab",
  "Agra": "Uttar Pradesh",
  "Nashik": "Maharashtra",
  "Faridabad": "Haryana",
  "Meerut": "Uttar Pradesh",
  "Rajkot": "Gujarat",
  "Kalyan-Dombivli": "Maharashtra",
  "Vasai-Virar": "Maharashtra",
  "Varanasi": "Uttar Pradesh",
  "Srinagar": "Jammu and Kashmir",
  "Aurangabad": "Maharashtra",
  "Dhanbad": "Jharkhand",
  "Amritsar": "Punjab",
  "Navi Mumbai": "Maharashtra",
  "Allahabad": "Uttar Pradesh",
  "Ranchi": "Jharkhand",
  "Howrah": "West Bengal",
  "Coimbatore": "Tamil Nadu",
  "Jabalpur": "Madhya Pradesh",
  "Gwalior": "Madhya Pradesh",
  "Vijayawada": "Andhra Pradesh",
  "Jodhpur": "Rajasthan",
  "Madurai": "Tamil Nadu",
  "Raipur": "Chhattisgarh",
  "Kota": "Rajasthan",
  "Guwahati": "Assam",
  "Chandigarh": "Chandigarh",
  "Solapur": "Maharashtra",
  "Hubli-Dharwad": "Karnataka",
  "Tiruchirappalli": "Tamil Nadu",
  "Bareilly": "Uttar Pradesh",
  "Mysore": "Karnataka",
  "Thiruvananthapuram": "Kerala",
  "Noida": "Uttar Pradesh",
  "Ghaziabad": "Uttar Pradesh",
  "Gurgaon": "Haryana",
  "Bhubaneswar": "Odisha",
  "Dehradun": "Uttarakhand",
  "Jamshedpur": "Jharkhand",
  "Asansol": "West Bengal",
  "Ajmer": "Rajasthan",
  "Udaipur": "Rajasthan",
  "Bikaner": "Rajasthan",
  "Aligarh": "Uttar Pradesh",
  "Moradabad": "Uttar Pradesh",
  "Gaya": "Bihar",
  "Muzaffarpur": "Bihar",
  "Bilaspur": "Chhattisgarh",
  "Panipat": "Haryana",
  "Rohtak": "Haryana",
  "Pondicherry": "Puducherry",
  "Siliguri": "West Bengal",
  "Durgapur": "West Bengal",
  "Nellore": "Andhra Pradesh",
  "Warangal": "Telangana",
  "Karimnagar": "Telangana",
  "Tirupati": "Andhra Pradesh",
  "Anantapur": "Andhra Pradesh",
  "Kurnool": "Andhra Pradesh",
  "Belgaum": "Karnataka",
  "Bellary": "Karnataka",
  "Davangere": "Karnataka",
  "Shimoga": "Karnataka",
  "Mangalore": "Karnataka",
  "Thrissur": "Kerala",
  "Kozhikode": "Kerala",
  "Kollam": "Kerala",
  "Alappuzha": "Kerala",
  "Imphal": "Manipur",
  "Aizawl": "Mizoram",
  "Itanagar": "Arunachal Pradesh",
  "Agartala": "Tripura",
  "Shillong": "Meghalaya",
  "Kohima": "Nagaland",
  "Port Blair": "Andaman and Nicobar Islands",
  "Panaji": "Goa",
  "Margao": "Goa",
  "Daman": "Daman and Diu",
  "Silvassa": "Dadra and Nagar Haveli and Daman and Diu",
  "Leh": "Ladakh",
  "Kargil": "Ladakh",
  "Rewa": "Madhya Pradesh",
  "Satna": "Madhya Pradesh"
}


USA_CITY_STATE = {
    "Milwaukee": "Wisconsin",
    "Albuquerque": "New Mexico",
    "Tucson": "Arizona",
    "Fresno": "California",
    "Mesa": "Arizona",
    "Sacramento": "California",
    "Atlanta": "Georgia",
    "Kansas City": "Missouri",
    "Colorado Springs": "Colorado",
    "Omaha": "Nebraska",
    "Raleigh": "North Carolina",
    "Miami": "Florida",
    "Long Beach": "California",
    "Virginia Beach": "Virginia",
    "Oakland": "California",
    "Minneapolis": "Minnesota",
    "Tulsa": "Oklahoma",
    "Arlington": "Texas",
    "Tampa": "Florida",
    "New Orleans": "Louisiana",
    "Wichita": "Kansas",
    "Cleveland": "Ohio",
    "Bakersfield": "California",
    "Aurora": "Colorado",
    "Anaheim": "California",
    "Honolulu": "Hawaii",
    "Santa Ana": "California",
    "Riverside": "California",
    "Corpus Christi": "Texas",
    "Lexington": "Kentucky",
    "Henderson": "Nevada",
    "Stockton": "California",
    "Saint Paul": "Minnesota",
    "Cincinnati": "Ohio",
    "St. Louis": "Missouri",
    "Pittsburgh": "Pennsylvania",
    "Greensboro": "North Carolina",
    "Lincoln": "Nebraska",
    "Anchorage": "Alaska",
    "Plano": "Texas",
    "Orlando": "Florida",
    "Irvine": "California",
    "Newark": "New Jersey",
    "Toledo": "Ohio",
    "Durham": "North Carolina",
    "Chula Vista": "California",
    "Fort Wayne": "Indiana",
    "Jersey City": "New Jersey",
    "St. Petersburg": "Florida",
    "Laredo": "Texas",
    "Madison": "Wisconsin",
    "Chandler": "Arizona",
    "Buffalo": "New York",
    "Lubbock": "Texas",
    "Scottsdale": "Arizona",
    "Reno": "Nevada",
    "Glendale": "Arizona",
    "Gilbert": "Arizona",
    "Winston–Salem": "North Carolina",
    "North Las Vegas": "Nevada",
    "Norfolk": "Virginia",
    "Chesapeake": "Virginia",
    "Garland": "Texas",
    "Irving": "Texas",
    "Hialeah": "Florida",
    "Fremont": "California",
    "Boise": "Idaho",
    "Richmond": "Virginia",
    "Baton Rouge": "Louisiana"
}
