# configs/hudi_config.py

HUDI_OPTIONS = {
    "hoodie.table.name": "users",
    "hoodie.datasource.write.recordkey.field": "id",
    "hoodie.datasource.write.precombine.field": "ingestion_time",
    "hoodie.datasource.write.operation": "upsert",
    "hoodie.datasource.write.table.type": "MERGE_ON_READ",
    "hoodie.datasource.write.keygenerator.class": "org.apache.hudi.keygen.ComplexKeyGenerator",
    "hoodie.datasource.write.partitionpath.field": "country,state,city",
    "hoodie.datasource.write.hive_style_partitioning": "false",
    "hoodie.datasource.hive_sync.enable": "true",
    "hoodie.datasource.hive_sync.mode": "hms",
    "hoodie.datasource.hive_sync.metastore.uris": "thrift://hive-metastore:9083",
    "hoodie.datasource.hive_sync.table": "users",
    "hoodie.datasource.hive_sync.database": "default",
    "hoodie.datasource.hive_sync.support_timestamp": "true",
    "hoodie.datasource.hive_sync.partition_fields": "country,state,city",
    "hoodie.datasource.hive_sync.partition_extractor_class": "org.apache.hudi.hive.MultiPartKeysValueExtractor",
    "hoodie.datasource.hive_sync.table_type": "MERGE_ON_READ",
    "hoodie.metadata.enable": "true",
    "hoodie.metadata.async.enable": "true",
    "hoodie.metadata.index.column.stats.enable": "true",
    "hoodie.metadata.index.bloom.enable": "true",
    "hoodie.metadata.index.file.name.enable": "true",
    "hoodie.metadata.index.column.stats.include": "firstname,email,country,state,city",
    "hoodie.index.type": "BUCKET",
    "hoodie.bucket.index.num.buckets": "8",
    "hoodie.bloom.index.update.partition.path": "true",
    "hoodie.parquet.max.file.size": "134217728",
    "hoodie.parquet.small.file.limit": "134217728",
    "hoodie.copyonwrite.insert.parallelism": "4",
    "hoodie.upsert.shuffle.parallelism": "4",
    "hoodie.layout.optim.enable": "true",
    "hoodie.layout.optim.strategy": "z-order",
    "hoodie.layout.optim.zorder.cols": "country,state,city",
    "hoodie.clean.automatic": "true",
    "hoodie.clean.async": "true",
    "hoodie.clustering.inline": "false",
    "hoodie.compact.inline.max.delta.commits": "2",
}
HUDI_BASE_PATH = "/hudi_output"